# Generated by Django 5.0.2 on 2024-02-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_sale_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_discount',
            new_name='discount',
        ),
    ]
